name: fuel_delivery_app_service_provider
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_ui_auth: ^1.14.0
  cloud_firestore: ^4.17.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  firebase_auth_rest: ^2.0.4
  flutter:
    sdk: flutter
  gap: ^3.0.1
  hexcolor: ^3.0.1
  intl_phone_field: ^3.2.0
  intl_phone_field2: ^3.3.4
  intl_phone_field_with_validator: ^0.2.0
  lottie: ^3.1.0  
  otp_text_field_v2: ^1.0.3
  google_login: ^1.0.3
  bloc_connectivity: ^0.0.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  google_nav_bar: ^5.0.6
  font_awesome_flutter: ^10.7.0
  flutter_onboarding_slider: ^1.0.11
  intro_screen_onboarding_flutter: ^1.0.0
  flutter_side_menu: ^0.5.3
  flml_web_sidemenu: ^0.0.3
  tab_container: ^3.5.3
  flutter_animate: ^4.5.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2

  file_picker: ^8.0.3
  path: ^1.9.0
  path_provider: ^2.1.3
  pdfrx: ^1.0.67
  easy_pdf_viewer: ^1.0.8
  map_location_picker: ^1.2.8+3
  location: ^6.0.2
  google_maps_flutter: ^2.7.0
  syncfusion_flutter_pdfviewer: ^24.2.8
  dotted_border: ^2.1.0
  http: ^1.2.1
  multi_image_picker_view:
    # path: custom_packages/multi_image_picker_view-1.0.2
  firebase_storage: ^11.7.7
  shared_preferences: ^2.2.3
  # multi_image_picker_view: ^1.0.2
                


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 
  fonts:
    - family: Lexend
      fonts:
        - asset: fonts/Lexend-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Lexend-Bold
      fonts:
        - asset: fonts/Lexend-Bold.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
    - family: Poppins
      fonts:
        - asset: fonts\Poppins-Black.ttf
