name: example
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  multi_image_picker_view:
    path: ../
  
  file_picker: ^6.1.1
  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
